"""Companion — Milestone 5: the bond."""

from .constraint import evaluate
from .dynamics import (
    PHASE_NOTES,
    PHASE_VOICE,
    PHASES,
    WOUND_AMPLIFIER,
    WOUND_SALIENCE,
    WOUND_TAGS,
    WOUND_WINDOW_DAYS,
    PhaseSpec,
    phase_notes,
    phase_voice_delta,
    update_phases,
    wound_amplifier,
)
from .embeddings import HashEmbedder, cosine, default_embedder
from .env import load_dotenv
from .items import Item, ItemRegistry, item_stimuli, load_items
from .llm import LLM, MockLLM, OpenAILLM, default_llm
from .loop import CompanionSession
from .methods import DEFAULT_METHODS, SELF_TOKENS, MethodRegistry, MethodSpec, outcome_for
from .memory import (
    apply_rehearsal,
    decay_rate_for,
    effective_salience,
    emotional_tags_for,
    episodic_memory,
    mood_tags,
    recency_score,
    relative_time,
    retrieve,
    write_salience,
)
from .models import (
    Activation,
    AffectState,
    AppliedReflection,
    DriftProposal,
    InsightProposal,
    Memory,
    Perception,
    ReflectionProposal,
    RelationshipVector,
    RetrievedMemory,
    Stimulus,
    Trait,
    TraitCategory,
    Trigger,
    TurnTrace,
    VoiceProfile,
    voice_delta,
)
from .perception import perceive
from .state import CompanionState
from .store import Store
from .traits import TraitRegistry, dislikes, likes
from .characters import (CHARACTER_TEMPLATES, CharacterManager,
                         CharacterSpec, CharacterSummary, Preference,
                         load_character, slugify, spec_warnings,
                         template_spec)
from .voice import compose_voice

__all__ = [
    "Activation",
    "AffectState",
    "AppliedReflection",
    "DriftProposal",
    "InsightProposal",
    "Item",
    "ItemRegistry",
    "item_stimuli",
    "load_items",
    "Memory",
    "Perception",
    "ReflectionProposal",
    "RelationshipVector",
    "RetrievedMemory",
    "Stimulus",
    "Trait",
    "TraitCategory",
    "Trigger",
    "TurnTrace",
    "VoiceProfile",
    "voice_delta",
    "TraitRegistry",
    "likes",
    "dislikes",
    "load_character",
    "perceive",
    "evaluate",
    "compose_voice",
    "CompanionState",
    "Store",
    "CompanionSession",
    "LLM",
    "MockLLM",
    "OpenAILLM",
    "default_llm",
    "HashEmbedder",
    "cosine",
    "default_embedder",
    "retrieve",
    "episodic_memory",
    "apply_rehearsal",
    "decay_rate_for",
    "effective_salience",
    "emotional_tags_for",
    "mood_tags",
    "recency_score",
    "relative_time",
    "write_salience",
    "MethodSpec",
    "MethodRegistry",
    "DEFAULT_METHODS",
    "SELF_TOKENS",
    "outcome_for",
    "load_dotenv",
    "PhaseSpec",
    "PHASES",
    "PHASE_VOICE",
    "PHASE_NOTES",
    "WOUND_TAGS",
    "WOUND_SALIENCE",
    "WOUND_WINDOW_DAYS",
    "WOUND_AMPLIFIER",
    "update_phases",
    "phase_voice_delta",
    "phase_notes",
    "wound_amplifier",
    "Preference",
    "CharacterSpec",
    "CharacterSummary",
    "CharacterManager",
    "CHARACTER_TEMPLATES",
    "template_spec",
    "spec_warnings",
    "slugify",
]
